apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: grpc-client
  name: grpc-client
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: grpc-client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: grpc-client
    spec:
      containers:
      - image: localhost:5000/grpc-client-istio:v0.5
        imagePullPolicy: IfNotPresent
        name: grpc-client
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
