// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld.proto

package helloworld

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HiRequest struct {
	ToWho                string   `protobuf:"bytes,1,opt,name=toWho,proto3" json:"toWho,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Clientip             string   `protobuf:"bytes,3,opt,name=clientip,proto3" json:"clientip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HiRequest) Reset()         { *m = HiRequest{} }
func (m *HiRequest) String() string { return proto.CompactTextString(m) }
func (*HiRequest) ProtoMessage()    {}
func (*HiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{0}
}

func (m *HiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HiRequest.Unmarshal(m, b)
}
func (m *HiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HiRequest.Marshal(b, m, deterministic)
}
func (m *HiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HiRequest.Merge(m, src)
}
func (m *HiRequest) XXX_Size() int {
	return xxx_messageInfo_HiRequest.Size(m)
}
func (m *HiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HiRequest proto.InternalMessageInfo

func (m *HiRequest) GetToWho() string {
	if m != nil {
		return m.ToWho
	}
	return ""
}

func (m *HiRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *HiRequest) GetClientip() string {
	if m != nil {
		return m.Clientip
	}
	return ""
}

type HiResponse struct {
	FromWho              string   `protobuf:"bytes,1,opt,name=fromWho,proto3" json:"fromWho,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Serverip             string   `protobuf:"bytes,3,opt,name=serverip,proto3" json:"serverip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HiResponse) Reset()         { *m = HiResponse{} }
func (m *HiResponse) String() string { return proto.CompactTextString(m) }
func (*HiResponse) ProtoMessage()    {}
func (*HiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{1}
}

func (m *HiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HiResponse.Unmarshal(m, b)
}
func (m *HiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HiResponse.Marshal(b, m, deterministic)
}
func (m *HiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HiResponse.Merge(m, src)
}
func (m *HiResponse) XXX_Size() int {
	return xxx_messageInfo_HiResponse.Size(m)
}
func (m *HiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HiResponse proto.InternalMessageInfo

func (m *HiResponse) GetFromWho() string {
	if m != nil {
		return m.FromWho
	}
	return ""
}

func (m *HiResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *HiResponse) GetServerip() string {
	if m != nil {
		return m.Serverip
	}
	return ""
}

func init() {
	proto.RegisterType((*HiRequest)(nil), "helloworld.HiRequest")
	proto.RegisterType((*HiResponse)(nil), "helloworld.HiResponse")
}

func init() { proto.RegisterFile("helloworld.proto", fileDescriptor_17b8c58d586b62f2) }

var fileDescriptor_17b8c58d586b62f2 = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0x48, 0xcd, 0xc9,
	0xc9, 0x2f, 0xcf, 0x2f, 0xca, 0x49, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0x88,
	0x48, 0xc9, 0xa4, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0x27, 0x16, 0x64, 0xea, 0x27, 0xe6, 0xe5,
	0xe5, 0x97, 0x24, 0x96, 0x64, 0xe6, 0xe7, 0x15, 0x43, 0x54, 0x2a, 0x85, 0x73, 0x71, 0x7a, 0x64,
	0x06, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x89, 0x70, 0xb1, 0x96, 0xe4, 0x87, 0x67, 0xe4,
	0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x38, 0x42, 0x12, 0x5c, 0xec, 0xb9, 0xa9, 0xc5,
	0xc5, 0x89, 0xe9, 0xa9, 0x12, 0x4c, 0x60, 0x71, 0x18, 0x57, 0x48, 0x8a, 0x8b, 0x23, 0x39, 0x27,
	0x33, 0x35, 0xaf, 0x24, 0xb3, 0x40, 0x82, 0x19, 0x2c, 0x05, 0xe7, 0x2b, 0xc5, 0x70, 0x71, 0x81,
	0x0c, 0x2e, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x05, 0x99, 0x91, 0x56, 0x94, 0x9f, 0x8b, 0x30, 0x1b,
	0xc6, 0xc5, 0x6f, 0x7a, 0x71, 0x6a, 0x51, 0x59, 0x6a, 0x11, 0xc2, 0x74, 0x18, 0xdf, 0x28, 0x88,
	0x8b, 0xd5, 0x03, 0xe4, 0x45, 0x21, 0x4f, 0x2e, 0x26, 0x8f, 0x4c, 0x21, 0x51, 0x3d, 0xa4, 0x20,
	0x80, 0xfb, 0x47, 0x4a, 0x0c, 0x5d, 0x18, 0xe2, 0x1a, 0x25, 0x91, 0xa6, 0xcb, 0x4f, 0x26, 0x33,
	0xf1, 0x29, 0x71, 0xea, 0x83, 0xe5, 0xf5, 0x33, 0x32, 0xad, 0x18, 0xb5, 0x92, 0xd8, 0xc0, 0x21,
	0x62, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xa4, 0xac, 0xfa, 0xe7, 0x4f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HelloClient is the client API for Hello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloClient interface {
	Hi(ctx context.Context, in *HiRequest, opts ...grpc.CallOption) (*HiResponse, error)
}

type helloClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloClient(cc grpc.ClientConnInterface) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) Hi(ctx context.Context, in *HiRequest, opts ...grpc.CallOption) (*HiResponse, error) {
	out := new(HiResponse)
	err := c.cc.Invoke(ctx, "/helloworld.Hello/Hi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServer is the server API for Hello service.
type HelloServer interface {
	Hi(context.Context, *HiRequest) (*HiResponse, error)
}

// UnimplementedHelloServer can be embedded to have forward compatible implementations.
type UnimplementedHelloServer struct {
}

func (*UnimplementedHelloServer) Hi(ctx context.Context, req *HiRequest) (*HiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hi not implemented")
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_Hi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).Hi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Hello/Hi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).Hi(ctx, req.(*HiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hi",
			Handler:    _Hello_Hi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld.proto",
}
